# Generated by Django 5.2.7 on 2025-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_blog_body_alter_blog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
